#!/bin/bash

set -euo pipefail
IFS=

for f in test/*.txt; do
    bn=$(basename "$f" .txt)
    out=$(dirname "$f")/$bn.out
    err=$(dirname "$f")/$bn.err
    target/debug/cj-hours-parser --debug-items "$f" > "$out" 2> "$err" || true
done

